### ISSUE TITLE
Make mobile dropdown cleaner

### ISSUE THREAD

**Issue by ashlab11** [BPR-Data-Team/ElectionModel2024-site#73]
Mobile dropdown is currently a different font from the rest of the page, and from the desktop version. We should make it look like the desktop version. Separately, we should eventually make both dropdowns look native to the website and not rely on what regular dropdowns look like on a computer, since the current dropdown doesn't fit the vibe of the website.

**Comment by arielshif** [comment]
for the developer working on this, here's some CSS to get you started:
```css
.class {
appearance: none; /* Removes default browser formatting */
font-family: use the same font stack as in the surrounding text;
color: var(--main-text-color);
background: transparent;
border-radius: pick something conservative;
border: something sensible, maybe in gradient descent grey;
make the border thicker and gubernatorial grey on active state;
drop shadow maybe if it's conservative and looks good;
}
``` 

the reason I didn't implement appearance: none to begin with was bc that got rid of the arrow in the dropdown and I didn't have time to figure out how to reinstate it
